### ISSUE TITLE
Nie umiem 4.3 pls help

### ISSUE THREAD

**Issue by NimVrod** [NimVrod/Matura_Odp#1]
![image](https://user-images.githubusercontent.com/84095520/143288165-8f5d17dd-5344-4fe9-989b-d5e62958ac13.png)

Halo jak zrobić wykres
Jak to dla każdego punktu (trzeba zamienić sumę na taba i z niego liczyć sadge)

**Comment by NimVrod** [comment]
Chyba zrobiłem #https://github.com/NimVrod/Matura_Odp/commit/3769648d63c847eab584ab2e2169bc9d284e54b3
ale nie jestem pewnien
zostało wczytanie z pliku

**Comment by M1hv** [comment]
ty ale z matury 2015/16/17 zadania z 4. sa do excela
a 6. są programowanie

**Comment by NimVrod** [comment]
aha ok

**Comment by NimVrod** [comment]
aha ok

**Comment by NimVrod** [comment]
W 2015 chyba nawet nie ma programowania
